# Generated by Django 3.2.4 on 2021-06-29 13:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminPiezas', '0004_alter_pieza_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paramedico',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fnln', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='pieza',
            name='nroPieza',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='pieza',
            name='paramedico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminPiezas.paramedico'),
        ),
    ]
