# Generated by Django 3.2.4 on 2021-06-29 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPiezas', '0005_auto_20210629_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paramedico',
            old_name='fnln',
            new_name='nombre',
        ),
    ]
