# Generated by Django 3.2.4 on 2021-07-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPiezas', '0007_auto_20210629_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramedico',
            name='fechaNacP',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='paramedico',
            name='rutP',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
